
defaults:
  - aa

diffuser:
  T: 200

inference:
  num_designs: 500
  model_runner: NRBStyleSelfCond
  ligand: 'HBA'

model:
  freeze_track_motif: True

contigmap:
  contigs: ["30-110,A64-64,30-110"]
  inpaint_str: null
  length: "100-140"

potentials:
  guiding_potentials: ["type:ligand_ncontacts,weight:1"] 
  guide_scale: 2
  guide_decay: cubic
